### ISSUE TITLE
now 15.3.0 issues, now dev not working

### ISSUE THREAD

**Issue by moflo** [vercel/vrs#6]
Is is possible to test both the frontend and backend using `now dev` command? Now v15.3.0 fails to run locally, with the backend build process failing:

```
>$ now dev
> Now CLI 15.3.0 dev (beta) — https://zeit.co/feedback/dev
> Setting up 1 Builder
> Success! Builder setup complete
> Ready! Available at http://localhost:3000
```

Open a local session at `http://localhost:5000/store` and then try to access the store contents, but the following error occurs:

```
request to https://localhost:3000/api/get-products failed, reason: write EPROTO 4474889664:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:
```

This seems due to the `/store` URL being assigned to `https://localhost:3000/api/get-products` in `store.js` line 75. If  you instead change the URL to `http://localhost:3000/api/get-products` you get a CORS error:

```
Failed to load resource: the server responded with a status of 500 (Internal Server Error) [http://localhost:3000/api/get-products]

Access to fetch at 'http://localhost:3000/api/get-products' from origin 'http://localhost:5000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled. [http://localhost:5000/]
```

Thanks.

**Comment by TooTallNate** [comment]
Could you try out `now-cli` 15.2.1-canary.4? I believe this issue has been fixed as of this release.

**Comment by moflo** [comment]
Hi, I'm using now-cli 15.3.0 but still have the error. Noticed the following error when pinging the api directly with CURL:

```
> GET /api/get-products
> Building @now/node:backend/api/get-products/index.js
downloading user files...
installing dependencies for user's code...
installing to /Users/xxx/Developer/GroupTalent/720shop/demo/vrs/backend/api/get-products
running user script...
running "yarn run now-build"
yarn run v1.15.2
warning package.json: No license field
$ npm run build
npm WARN lifecycle The node binary used for scripts is /var/folders/gj/9v560js88xl9nt001s6yp9c00000gr/T/yarn--1559176628890-0.611400404788687/node but npm is using /Users/xxx/Library/Caches/co.zeit.fun/runtimes/nodejs8.10/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> @ build /Users/xxx/Developer/GroupTalent/720shop/demo/vrs/backend
> next build

sh: next: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! @ build: `next build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I'll investigate using the `--scripts-prepend-node-path` command but perhaps I'm having a local conflict between npm and yarn. Thanks.

**Comment by leerob** [comment]
Closing as stale - thank you for reporting, though 🙏
